-- NOT İSTASYONU: BİLDİRİM + ADMİN SİSTEMİ
-- 1) Supabase Dashboard > Authentication > Providers bölümünden Anonymous Sign-Ins'i aç.
-- 2) Yönetici olacak ilk hesabı Authentication > Users üzerinden oluştur (veya uygulamadaki yönetici girişinden oluştur).
-- 3) Aşağıdaki SQL'i çalıştır.
-- 4) En altta YOUR_ADMIN_EMAIL yerine ilk admin hesabının e-postasını yazıp tekrar çalıştır.

create table if not exists public.app_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_id text not null,
  username text not null default 'Kullanıcı',
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists app_profiles_player_id_idx on public.app_profiles(player_id);

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.app_messages (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 2000),
  target_user_id uuid references auth.users(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.app_message_reads (
  message_id bigint not null references public.app_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (message_id,user_id)
);

create index if not exists app_messages_target_user_idx on public.app_messages(target_user_id,created_at desc);
create index if not exists app_messages_created_at_idx on public.app_messages(created_at desc);
create index if not exists app_message_reads_user_idx on public.app_message_reads(user_id,message_id);

create schema if not exists private;

create or replace function private.is_admin()
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_admin() from public;

alter table public.app_profiles enable row level security;
alter table public.app_admins enable row level security;
alter table public.app_messages enable row level security;
alter table public.app_message_reads enable row level security;

revoke all on table public.app_profiles from anon;
revoke all on table public.app_admins from anon;
revoke all on table public.app_messages from anon;
revoke all on table public.app_message_reads from anon;

grant select,insert,update on public.app_profiles to authenticated;
grant select on public.app_admins to authenticated;
grant select,insert,delete on public.app_messages to authenticated;
grant select,insert,update,delete on public.app_message_reads to authenticated;

-- Profiller: kullanıcı kendi profilini yönetir; admin herkesi görür.
drop policy if exists app_profiles_select on public.app_profiles;
create policy app_profiles_select on public.app_profiles
for select to authenticated
using ((select auth.uid()) = user_id or (select private.is_admin()));

drop policy if exists app_profiles_insert on public.app_profiles;
create policy app_profiles_insert on public.app_profiles
for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists app_profiles_update on public.app_profiles;
create policy app_profiles_update on public.app_profiles
for update to authenticated
using ((select auth.uid()) = user_id or (select private.is_admin()))
with check ((select auth.uid()) = user_id or (select private.is_admin()));

-- Admin listesi: sadece adminler okuyabilir/yönetebilir.
drop policy if exists app_admins_select on public.app_admins;
create policy app_admins_select on public.app_admins
for select to authenticated
using ((select private.is_admin()));

drop policy if exists app_admins_insert on public.app_admins;
create policy app_admins_insert on public.app_admins
for insert to authenticated
with check ((select private.is_admin()));

drop policy if exists app_admins_delete on public.app_admins;
create policy app_admins_delete on public.app_admins
for delete to authenticated
using ((select private.is_admin()));

-- Mesajları sadece hedef kişi veya herkes alır; admin hepsini görür.
drop policy if exists app_messages_select on public.app_messages;
create policy app_messages_select on public.app_messages
for select to authenticated
using (
  target_user_id is null
  or target_user_id = (select auth.uid())
  or (select private.is_admin())
);

drop policy if exists app_messages_insert on public.app_messages;
create policy app_messages_insert on public.app_messages
for insert to authenticated
with check ((select private.is_admin()) and created_by = (select auth.uid()));

drop policy if exists app_messages_delete on public.app_messages;
create policy app_messages_delete on public.app_messages
for delete to authenticated
using ((select private.is_admin()));

-- Okundu kayıtları yalnızca kullanıcının kendi satırlarına açıktır.
drop policy if exists app_message_reads_select on public.app_message_reads;
create policy app_message_reads_select on public.app_message_reads
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists app_message_reads_insert on public.app_message_reads;
create policy app_message_reads_insert on public.app_message_reads
for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists app_message_reads_update on public.app_message_reads;
create policy app_message_reads_update on public.app_message_reads
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists app_message_reads_delete on public.app_message_reads;
create policy app_message_reads_delete on public.app_message_reads
for delete to authenticated
using ((select auth.uid()) = user_id);

-- İlk yöneticiyi bir kez ata:
-- insert into public.app_admins(user_id)
-- select id from auth.users where lower(email) = lower('YOUR_ADMIN_EMAIL')
-- on conflict do nothing;
